[[headers]]
  for = "/*" # Applies to all paths
    [headers.access_control_allow_origin]
      origin = "*"
      methods = ["GET", "POST"]

[[redirects]]
  from = "/functions/*"
  to = "/functions/:splat"
  status = 200
